# Generated by Django 3.0.2 on 2020-01-24 23:47

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Credit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rx_type', models.CharField(choices=[('in patient', 'in Patient'), ('out patient', 'out patient')], max_length=255)),
                ('card', models.FloatField(default=0.0)),
                ('lab', models.FloatField(default=0.0)),
                ('x_ray', models.FloatField(default=0.0)),
                ('others', models.FloatField(default=0.0)),
                ('bed', models.FloatField(default=0.0)),
                ('ultrasound', models.FloatField(default=0.0)),
                ('medication', models.FloatField(default=0.0)),
                ('created_by', models.CharField(default='Me', max_length=255)),
                ('created_date', models.DateField(default=django.utils.timezone.now, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_first_name', models.CharField(default='', max_length=255)),
                ('patient_father_name', models.CharField(default='', max_length=255)),
                ('patient_grand_father_name', models.CharField(default='', max_length=255)),
                ('patient_gender', models.CharField(choices=[('female', 'female'), ('male', 'male')], default='', max_length=255)),
                ('patient_age', models.IntegerField(default=1)),
                ('h_in_id', models.CharField(default='', max_length=255, verbose_name='H/IN/ID')),
                ('mrn', models.CharField(default='', max_length=255)),
                ('patient_credit', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='registration.Credit')),
            ],
        ),
    ]
