# Generated by Django 3.0.2 on 2020-01-25 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='patient_address',
            field=models.CharField(default='', max_length=255),
        ),
    ]
