# Generated by Django 3.0.2 on 2020-03-14 02:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0002_patient_patient_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='patient_credit',
        ),
        migrations.AddField(
            model_name='credit',
            name='patient',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='registration.Patient'),
        ),
    ]
